breaking(ProjectCard): Use area and location from FPM
treely/strapi-slices pull request #24
Opened 2024-01-11 08:45 UTC by raulsteurer

BREAKING CHANGE: This requires that the area and location are set in the FPM. Futhermore, a thumbnail image and a certification state need to be set in Strapi.

2024-01-11 09:14 UTC, lukasbals requested changes

2024-01-11 09:14 UTC, lukasbals commented on src/hooks/useCreditsAvailableText/useCreditsAvailableText.tsx
Why a hook and not a component? 

I think in general a hook should not depend on messages.

2024-01-11 09:14 UTC, lukasbals commented on src/components/CreditsAvailableBadge/CreditsAvailableBadge.tsx
> +    }),
To be honest I liked the old solution better since I don't think we should use hooks to return texts of components.

2024-01-11 09:14 UTC, lukasbals commented on src/components/CreditsAvailableBadge/CreditsAvailableBadge.tsx
> +    }),
I would just wrap the `variants` from the old solution with a `useMemo` to not rerender it every time the component is rendered and use the `variants[status].color` directly instead of creating a const `variant`.

2024-01-11 12:53 UTC, raulsteurer commented on src/hooks/useCreditsAvailableText/useCreditsAvailableText.tsx
I made it a hook because the `ProjectCard` `footerTitle` only accepts a string.
But I agree that the hook is too much of an abstraction.

2024-01-15 11:19 UTC, lukasbals commented on src/slices/ProjectsGrid/ProjectsGrid.stories.tsx
>  import { storybookStrapiCoverMock } from '../../test/storybookMocks/storybookStrapiMedia';
!

2024-01-15 11:19 UTC, lukasbals commented on src/slices/ProjectsGrid/ProjectsGrid.stories.tsx
> +import fpmProjectMock from '../../test/integrationMocks/fpmProjectMock';
!

2024-01-15 11:19 UTC, lukasbals commented on src/slices/ProjectsGrid/ProjectsGrid.stories.tsx
>  const card = {
!

2024-01-15 11:19 UTC, lukasbals commented on src/slices/TextWithCard/TextWithCard.test.tsx
>    it('displays a card if there is a card in the slice', () => {
This could be more suitable.

2024-01-15 11:19 UTC, lukasbals commented on src/test/strapiMocks/strapiProjectCard.ts
Unneeded imports

2024-01-15 13:17 UTC, lukasbals approved these changes

2024-01-15 13:23 UTC, merged